### ISSUE TITLE
Lack of timeout on send

### ISSUE THREAD

**Issue by shipperizer** [mattupstate/flask-mail#114]
Not sure it's a major issue and maybe not even a minor, 
but let's say that the configuration is the following 
```yaml
    MAIL_SERVER: smtp.gmail.com
    MAIL_USE_TLS: False
    MAIL_USE_SSL: False
    MAIL_PORT: 666
    MAIL_USERNAME: wallaby@gmail.com
    MAIL_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxxxx 
```
and all the settings are basically wrong as the email is non existent and the password as well, the port is a random one.
What happens is that when I try to send a Message, the server hangs for 4m and  20s, and it's really stuck. 
As you can see below, the POST logging is delayed of that amount of time (and it's basically when I create the message, POST the form, create the Message and send it)
```log
127.0.0.1 - - [09/Jul/2015 13:04:20] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2015 13:08:41] "POST /register HTTP/1.1" 500 -
127.0.0.1 - - [09/Jul/2015 13:08:42] "GET /home HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2015 13:08:42] "GET /home HTTP/1.1" 200 -
```
Would it be possible to configure a timeout of 20sec after which you simply return with an error?
